POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aGFuYSIsImlkIjoiNWViMTIzNTcyZDViYjA1YjE4MmYzNGE1IiwiaWF0IjoxNTg4OTI1NjczfQ.YRu5Dobd8TVNVdKqoTL5VaWLGkAt6pmzX6d185WcYDI

{
    "title": "superb",
    "author": "super",
    "url": "super",
    "likes": 1234,
    "userId": "5eb117443de49f55680f538b"
}